# Generated by Django 2.2.6 on 2019-10-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=50)),
                ('category_image', models.ImageField(blank=True, default='images/sample-1.jpg', null=True, upload_to='images/category/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
