# Generated by Django 2.2.6 on 2019-10-14 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quessubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=100)),
                ('series_summary', models.CharField(max_length=200)),
                ('series_slug', models.CharField(default=1, max_length=50)),
                ('series_image', models.ImageField(blank=True, default='images/sample-1.jpg', null=True, upload_to='images/series/')),
                ('category_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.QuesSubject', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
    ]
