# Generated by Django 2.2.6 on 2019-10-14 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(max_length=150, verbose_name='Content Title')),
                ('paper_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('paper_slug', models.CharField(default=1, max_length=50)),
                ('paper_image', models.ImageField(blank=True, default='images/sample-1.jpg', null=True, upload_to='images/essay/', verbose_name='Display Image(Optional)')),
                ('series_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.SubSeries', verbose_name='Series')),
            ],
        ),
    ]
