# Generated by Django 2.2.6 on 2019-10-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='paper_image',
        ),
    ]
