# Generated by Django 2.2.6 on 2019-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_paper_paper_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prank_image', models.ImageField(blank=True, default='images/h1.jpg', null=True, upload_to='images/prank/')),
            ],
        ),
    ]
