# Generated by Django 2.2.6 on 2019-10-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_prank'),
    ]

    operations = [
        migrations.AddField(
            model_name='prank',
            name='prank_title',
            field=models.CharField(default='prank animal images', max_length=50, verbose_name='Image Title'),
        ),
    ]
