# Generated by Django 2.2.6 on 2019-10-15 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_prank_prank_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=0, verbose_name='Hit Counter')),
                ('latest_count', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
            ],
        ),
    ]
